# Generated by Django 5.2 on 2025-04-17 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_cart', '0003_estimation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comit', models.CharField(max_length=1000)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_cart.product')),
            ],
        ),
    ]
