# Generated by Django 5.2 on 2025-04-20 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_cart', '0004_comit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer_comit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=1000)),
                ('comit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_cart.comit')),
            ],
        ),
    ]
