# Generated by Django 5.2 on 2025-05-01 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_cart', '0005_answer_comit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
            ],
        ),
    ]
