# Generated by Django 5.2 on 2025-05-05 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_cart', '0006_clik'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plyer', models.CharField(max_length=1000)),
            ],
        ),
    ]
