# Generated by Django 5.2 on 2025-05-12 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_cart', '0008_remove_plyer_plyer_clik_plaer_plyer_ip'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=1)),
                ('plaer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_cart.plyer')),
            ],
        ),
    ]
